name: status
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  horizontal_card_pager: ^1.1.1
  permission_handler: ^8.1.6
  path_provider: ^2.0.5
  image_gallery_saver: ^1.7.1
  gallery_saver: ^2.3.2
  share: ^2.0.4
  flutter_staggered_grid_view:
  dio:
  chewie:
  image_picker: ^0.8.4+4
  thumbnails:
  video_player:
  file_picker: ^4.2.0
  video_controls: ^0.1.0
  flutter_whatsapp_stickers: ^1.0.1+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - sticker_packs/sticker_packs.json
    - sticker_packs/1/
    
